import { ConversionRatioConfig } from "../typedefs";

export const NANOSECOND_TO_MS_CONVERSION_RATIO: number = 1 / 1e6;
export const MICROSECOND_TO_MS_CONVERSION_RATIO: number = 1 / 1000;
export const SECOND_TO_MS_CONVERSION_RATIO: number = 1000;
export const MINUTE_TO_MS_CONVERSION_RATIO: number = 60 * SECOND_TO_MS_CONVERSION_RATIO;
export const HOUR_TO_MS_CONVERSION_RATIO: number = 60 * MINUTE_TO_MS_CONVERSION_RATIO;
export const WORKDAY_TO_MS_CONVERSION_RATIO: number = 8 * HOUR_TO_MS_CONVERSION_RATIO;
export const WORKWEEK_TO_MS_CONVERSION_RATIO: number = 5 * WORKDAY_TO_MS_CONVERSION_RATIO;
export const WORKMONTH_TO_MS_CONVERSION_RATIO: number = 4 * WORKWEEK_TO_MS_CONVERSION_RATIO;

export const DEFAULT_CONVERSION_RATIOS: ConversionRatioConfig = {
  ns: NANOSECOND_TO_MS_CONVERSION_RATIO,
  μs: MICROSECOND_TO_MS_CONVERSION_RATIO,
  ms: 1,
  s: SECOND_TO_MS_CONVERSION_RATIO,
  m: MINUTE_TO_MS_CONVERSION_RATIO,
  h: HOUR_TO_MS_CONVERSION_RATIO,
  d: WORKDAY_TO_MS_CONVERSION_RATIO,
  w: WORKWEEK_TO_MS_CONVERSION_RATIO,
  mo: WORKMONTH_TO_MS_CONVERSION_RATIO,
};
