import { ConversionRatioConfig } from "../typedefs/index";

export const SECOND_TO_MS_CONVERSION_RATIO: number = 1000;
export const MINUTE_TO_MS_CONVERSION_RATIO: number = 60 * SECOND_TO_MS_CONVERSION_RATIO;
export const HOUR_TO_MS_CONVERSION_RATIO: number = 60 * MINUTE_TO_MS_CONVERSION_RATIO;
export const DAY_TO_MS_CONVERSION_RATIO: number = 24 * HOUR_TO_MS_CONVERSION_RATIO;
export const WEEK_TO_MS_CONVERSION_RATIO: number = 7 * DAY_TO_MS_CONVERSION_RATIO;
export const YEAR_TO_MS_CONVERSION_RATIO: number = 365.25 * DAY_TO_MS_CONVERSION_RATIO;
export const MONTH_TO_MS_CONVERSION_RATIO: number = YEAR_TO_MS_CONVERSION_RATIO / 12;

export const DEFAULT_CONVERSION_RATIOS: ConversionRatioConfig = {
  ms: 1,
  s: SECOND_TO_MS_CONVERSION_RATIO,
  m: MINUTE_TO_MS_CONVERSION_RATIO,
  h: HOUR_TO_MS_CONVERSION_RATIO,
  d: DAY_TO_MS_CONVERSION_RATIO,
  w: WEEK_TO_MS_CONVERSION_RATIO,
  mo: MONTH_TO_MS_CONVERSION_RATIO,
  y: YEAR_TO_MS_CONVERSION_RATIO
};
